name: war_gaming
description: Team-based 2D mobile war game with online and Bluetooth multiplayer.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  web_socket_channel: ^2.4.0
  nearby_connections: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
